rancher:
  hostname: rancher.9.163.152.197.sslip.io
  bootstrapPassword: admin123
  ingress:
    tls:
      source: secret
      secretName: tls-rancher-ingress
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx