kibana:
  elasticsearchHosts: "https://elasticsearch-master:9200"
  
  # Security settings
  security:
    enabled: true
    tls:
      enabled: true
      verificationMode: certificate
  
  elasticsearch:
    ssl:
      verificationMode: certificate
      certificateAuthorities: "/usr/share/kibana/config/certs/ca.crt"
  
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: kibana.9.163.152.197.sslip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: kibana-tls
        hosts:
          - kibana.9.163.152.197.sslip.io

  extraInitContainers:
    - name: copy-elasticsearch-certs
      image: busybox
      command: ['sh', '-c', 'cp /usr/share/elasticsearch/config/certs/ca.crt /usr/share/kibana/config/certs/']
      volumeMounts:
        - name: elasticsearch-certs
          mountPath: /usr/share/elasticsearch/config/certs
        - name: kibana-certs
          mountPath: /usr/share/kibana/config/certs

  extraVolumes:
    - name: elasticsearch-certs
      secret:
        secretName: elasticsearch-master-certs
    - name: kibana-certs
      emptyDir: {}

  extraVolumeMounts:
    - name: kibana-certs
      mountPath: /usr/share/kibana/config/certs