kibana:
  elasticsearchHosts: "https://elasticsearch-master:9200"
  
  elasticsearchCertificateSecret: elasticsearch-master-certs
  
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "rancher-ca"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - host: kibana.9.163.152.197.sslip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: kibana-tls
        hosts:
          - kibana.9.163.152.197.sslip.io
  
  elasticsearchCredentials:
    secretName: elasticsearch-master-credentials
  
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"