kibana:
  elasticsearchHosts: "http://elasticsearch-master:9200"
  
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: kibana.9.163.152.197.sslip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: kibana-tls
        hosts:
          - kibana.9.163.152.197.sslip.io