apiVersion: v2
name: nginx-ingress-wrapper
description: A Helm chart for nginx ingress controller
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.9.0
    repository: https://kubernetes.github.io/ingress-nginx