ingress-nginx:
  controller:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      externalTrafficPolicy: Local

    config:
      use-forwarded-headers: "true"
      ssl-redirect: "true"
      force-ssl-redirect: "true"
      enable-real-ip: "true"
      proxy-buffer-size: "16k"
      proxy-body-size: "50m"
      strict-ssl: "false"  
      ssl-protocols: "TLSv1.2 TLSv1.3"  

    extraArgs:
      default-ssl-certificate: "cattle-system/tls-rancher" 

    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80