cert-manager:
  installCRDs: true

rancher:
  hostname: rancher.9.163.152.197.nip.io
  bootstrapPassword: admin123
  ingress:
    tls:
      source: rancher
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  replicas: 1