apiVersion: v2
name: kube-prometheus-stack-wrapper
description: A Helm chart for Prometheus Stack
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: https://prometheus-community.github.io/helm-charts