kube-prometheus-stack:
  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.9.163.152.197.sslip.io
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.9.163.152.197.sslip.io
            
    additionalDataSources:
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        url: https://elasticsearch-master:9200
        database: "[logstash-]YYYY.MM.DD"
        jsonData:
          esVersion: 8.5.1
          timeField: "@timestamp"
          tlsSkipVerify: true
          
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'elasticsearch'
          orgId: 1
          folder: 'Elasticsearch'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/elasticsearch

    dashboards:
      elasticsearch:
        elasticsearch-cluster-monitoring:
          gnetId: 266  
          revision: 2
          datasource: Elasticsearch

  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.9.163.152.197.sslip.io
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.9.163.152.197.sslip.io